name: audio_recorder_example
description: Demonstrates how to use the audio_recorder plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0
  file: ^5.0.4
  permission_handler: ^5.0.1+1


dev_dependencies:
  audio_recorder:
    path: ../
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true